name: estetika_ui
description: "estetika mobile ui"

# Prevent accidental publishing to pub.dev
publish_to: "none"

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  icons_plus: ^4.0.0
  flutter_carousel_slider: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  percent_indicator: ^4.2.5
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: assets/images/mosslogo.png
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/images/mosslogo.png
    background_color: "#ffffff"
    theme_color: "#21413A"
  windows:
    generate: true
    image_path: assets/images/mosslogo.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/images/mosslogo.png

flutter:
  assets:
    - assets/images/
    - assets/fonts/

  # Fonts
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
